// ============================================================
// MotoSPEC reference-bike encodings
// Source of truth: /motospec-style-table.csv
// ============================================================
//
// CSV column → preset mapping (one preset's results per bike):
//   R7 column     → "Sag"        (Front_Pot=30, Rear_Pot=10, Lean=0)
//   GSX-8R column → "Braking"    (Front_Pot=120, Rear_Pot=2, Lean=0)
//   RS660 column  → "Mid-Corner" (Front_Pot=80, Rear_Pot=20, Lean=55)
//
// `expected.<preset>` is populated only for the preset the CSV gives;
// other presets are `null` to avoid inventing values.

// Linkage coordinates: PLACEHOLDER — replace with real linkage geometry
// from service manual or tuner spec sheet (Phase C Task 1).
const PLACEHOLDER_LINKAGE = {
  Frame_Rocker_Pivot_X: -50,  Frame_Rocker_Pivot_Y: 80,
  Rocker_To_Shock_X:    -65,  Rocker_To_Shock_Y:    100,
  Rocker_To_Drag_X:     -45,  Rocker_To_Drag_Y:     60,
  Drag_To_Swingarm_X:    40,  Drag_To_Swingarm_Y:   -10,
  Frame_Shock_Top_X:    -200, Frame_Shock_Top_Y:    300,
};

// Common dynamic presets (one row in CSV applied across all three bikes)
const DYNAMIC_PRESETS = {
  sag:        { Travel_Front: 30,  Travel_Rear: 10, Lean_Angle: 0  },
  braking:    { Travel_Front: 120, Travel_Rear: 2,  Lean_Angle: 0  },
  mid_corner: { Travel_Front: 80,  Travel_Rear: 20, Lean_Angle: 55 },
};

export const REFERENCE_BIKES = [
  {
    id: 'r7',
    name: 'Yamaha R7 2022',
    fork_name: 'FGK242',
    shock_name: 'YA 589',
    swingarm_name: 'Yamaha R7 2022',
    link_name: 'R7',
    front_tire: 'Pir SBK 120/70',
    rear_tire: 'Pir SBK 180/60',
    inputs: {
      // FRONT SETTINGS
      Yoke_Offset: 35,
      Fork_Position: 5,
      Front_Spring_Rate: 9.0,
      Front_Spring_Preload: 10.0,
      Front_Oil_Level: 170.0,
      Front_Topout_Rate: 4.0,
      Front_Topout_Length: 40.0,
      // REAR SETTINGS
      Swingarm_Length: 533,
      Shock_Clevis_RHA: 0,
      Shock_Length: 310,
      Rear_Spring_Rate: 110,
      Rear_Spring_Preload: 14,
      Rear_Topout_Rate: 188,
      Rear_Topout_Length: 8,
      Linkarm_Length: 92,
      // SPROCKETS
      Front_Sprocket: 16,
      Rear_Sprocket: 42,
      // Linkage placeholder coords
      ...PLACEHOLDER_LINKAGE,
      // Existing-app inputs (plausible defaults)
      Rake_Static: 24,
      Rf: 310,
      O: 32,
      Mass: 280,
      H_CG: 650,
      L_CG: 750,
      WB: 1400,
      front_weight_dist: 0.52,
      rear_weight_dist: 0.48,
      beta_static: 14,
      L_SA: 580,
      theta_chain: 15,
      a_x: 0.5,
      rho: 1.225,
      V: 30,
      Cd: 0.4,
      A: 0.5,
      C_f_aero: 0.4,
      C_r_aero: 0.6,
      Travel_Front: 30,
      Travel_Rear: 10,
    },
    dynamic_presets: DYNAMIC_PRESETS,
    expected: {
      sag: {
        Rake: 24.27,
        Ground_Trail: 97.8,
        Rear_Wheel_Vertical_Travel: 25.2,
        Rear_Ride_Height: -77.6,
        Swingarm_Angle: -8.37,
        AntiSquat_Pct: 109.2,
        Progression_Pct: 16.9,
        Motion_Ratio: 2.488,
        Wheelbase: 1403.5,
        Front_Wheel_Rate: 33.74,
        Rear_Wheel_Rate: 18.97,
        Front_Wheel_Force: 754.9,
        Rear_Wheel_Force: 1151.3,
        CofG_Front_Pct: 44.6,
        CofG_Rear_Pct: 55.4,
      },
      braking: null,
      mid_corner: null,
    },
  },
  {
    id: 'gsx8r',
    name: 'Suzuki GSX-8R 2024',
    fork_name: 'Showa',
    shock_name: 'Showa',
    swingarm_name: 'Suzuki GSX-8R 2024',
    link_name: 'STOCK',
    front_tire: 'Pir SBK 120/70',
    rear_tire: 'Pir SBK 180/60',
    inputs: {
      Yoke_Offset: 30,
      Fork_Position: 0,
      Front_Spring_Rate: 8.5,
      Front_Spring_Preload: 10.0,
      Front_Oil_Level: 180.0,
      Front_Topout_Rate: 4.0,
      Front_Topout_Length: 40.0,
      Swingarm_Length: 586.4,
      Shock_Clevis_RHA: 0,
      Shock_Length: 309.6,
      Rear_Spring_Rate: 135,
      Rear_Spring_Preload: 15,
      Rear_Topout_Rate: 188,
      Rear_Topout_Length: 8,
      Linkarm_Length: 128.9,
      Front_Sprocket: 17,
      Rear_Sprocket: 47,
      ...PLACEHOLDER_LINKAGE,
      Rake_Static: 25,
      Rf: 310,
      O: 32,
      Mass: 295,
      H_CG: 650,
      L_CG: 760,
      WB: 1430,
      front_weight_dist: 0.52,
      rear_weight_dist: 0.48,
      beta_static: 14,
      L_SA: 586.4,
      theta_chain: 15,
      a_x: 0.5,
      rho: 1.225,
      V: 30,
      Cd: 0.4,
      A: 0.5,
      C_f_aero: 0.4,
      C_r_aero: 0.6,
      Travel_Front: 120,
      Travel_Rear: 2,
    },
    dynamic_presets: DYNAMIC_PRESETS,
    expected: {
      sag: null,
      braking: {
        Rake: 21.09,
        Ground_Trail: 84.3,
        Rear_Wheel_Vertical_Travel: 5.3,
        Rear_Ride_Height: -63.4,
        Swingarm_Angle: -6.21,
        AntiSquat_Pct: 98.8,
        Progression_Pct: 34,
        Motion_Ratio: 2.672,
        Wheelbase: 1430.9,
        Front_Wheel_Rate: 28.96,
        Rear_Wheel_Rate: 45.91,
        Front_Wheel_Force: 2801.6,
        Rear_Wheel_Force: 469.2,
        CofG_Front_Pct: 53.6,
        CofG_Rear_Pct: 46.4,
      },
      mid_corner: null,
    },
  },
  {
    id: 'rs660',
    name: 'Aprilia RS 660 Factory 2025',
    fork_name: 'FL 23030',
    shock_name: 'AP660',
    swingarm_name: 'Aprilia RS 660 Factory 2025',
    link_name: '',
    front_tire: 'Pir SBK 120/70',
    rear_tire: 'Pir SBK 180/60',
    inputs: {
      Yoke_Offset: 28,
      Fork_Position: 10,
      Front_Spring_Rate: 9.5,
      Front_Spring_Preload: 5.0,
      Front_Oil_Level: 125.0,
      Front_Topout_Rate: 3.5,
      Front_Topout_Length: 40.0,
      Swingarm_Length: 546.3,
      Shock_Clevis_RHA: 0,
      Shock_Length: 309,
      Rear_Spring_Rate: 160,
      Rear_Spring_Preload: 7,
      Rear_Topout_Rate: 0,
      Rear_Topout_Length: 0,
      Linkarm_Length: 0,
      Front_Sprocket: 17,
      Rear_Sprocket: 43,
      ...PLACEHOLDER_LINKAGE,
      Rake_Static: 24,
      Rf: 310,
      O: 32,
      Mass: 285,
      H_CG: 650,
      L_CG: 740,
      WB: 1370,
      front_weight_dist: 0.52,
      rear_weight_dist: 0.48,
      beta_static: 14,
      L_SA: 546.3,
      theta_chain: 15,
      a_x: 0.5,
      rho: 1.225,
      V: 30,
      Cd: 0.4,
      A: 0.5,
      C_f_aero: 0.4,
      C_r_aero: 0.6,
      Travel_Front: 80,
      Travel_Rear: 20,
    },
    dynamic_presets: DYNAMIC_PRESETS,
    expected: {
      sag: null,
      braking: null,
      mid_corner: {
        Rake: 21.13,
        Ground_Trail: 76.7,
        Rear_Wheel_Vertical_Travel: 52,
        Rear_Ride_Height: -46.3,
        Swingarm_Angle: -4.86,
        AntiSquat_Pct: 88.3,
        Progression_Pct: 5.2,
        Motion_Ratio: 2.584,
        Wheelbase: 1360.7,
        Front_Wheel_Rate: 31.85,
        Rear_Wheel_Rate: 24.61,
        Front_Wheel_Force: 2087.8,
        Rear_Wheel_Force: 1781.3,
        CofG_Front_Pct: 52.4,
        CofG_Rear_Pct: 47.6,
      },
    },
  },
];
